version: '3.8'

services:
  app: 
    build: 
      context: .
      dockerfile: Dockerfile 
      args: 
        VARIANT: "bullseye"
        PHP_VERSION: "7.4"
    volumes:
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends. 
    command: sleep infinity
    # network_mode: service:db

  db: # 3306
    image: mariadb:10.7
    restart: unless-stopped
    volumes: 
      - mariadb-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    network_mode: service:app
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  mailhog: # 1025 - SMTP, 8025 - HTTP
    image: mailhog/mailhog
    restart: unless-stopped
    network_mode: service:app

    # Add "forwardPorts": ["1025", "8025"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  mariadb-data: